[[Tokei]]
arch = "aarch64"
git-tree-sha1 = "ff0166bb4ddde4b6e0ce433358c6fba531b561ce"
os = "macos"

    [[Tokei.download]]
    sha256 = "f5690cca9c9f2975da52c720ed52bd9299e148629a178b31a1e0bbf9a6243f30"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.aarch64-apple-darwin.tar.gz"
[[Tokei]]
arch = "aarch64"
git-tree-sha1 = "1e26123f625ad44c8093f0559d56eb5278dc9335"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "aec6e9482731f0e0e8c8c1d3b3803ac2819fe9713dc4bfa1b264f6fb79258bc2"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.aarch64-linux-gnu.tar.gz"
[[Tokei]]
arch = "aarch64"
git-tree-sha1 = "a96adb5cfbdc32ddff338fee7bda566d3a0ffaf2"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "98299e079e58926ace91e4a2c5ef831c595e5388622238f36d2ef9cca93d389f"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.aarch64-linux-musl.tar.gz"
[[Tokei]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "721c1285d69eb7006ee9f4f242bd6cb0d67e00ce"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "363f96689ec8b74ec947c0c7e5aa288e6b270caab4b19cc93e0d74e21968c66b"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.armv6l-linux-gnueabihf.tar.gz"
[[Tokei]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "317164b9b4adac1527307608bc2ab939d44bb9cd"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "bd87be3d5617bcdb30adef62080bad0bf4efb709e7b9d879fcf9bdbe7b25570a"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.armv6l-linux-musleabihf.tar.gz"
[[Tokei]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de30cd0f5d941cf905a2dbc44a0e47a7105cea78"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "7a9a99392e75ed6dff07e4388673add24b537637924f73e81cd0cf251a47b7bc"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.armv7l-linux-gnueabihf.tar.gz"
[[Tokei]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2f8c621a3cba52ad90dfd964f2067cea46e18fc"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "5edd23bfbd8dd8a76bfff3c4ac55facc6df97320f6bcf7b7c3ad0828e66ab11c"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.armv7l-linux-musleabihf.tar.gz"
[[Tokei]]
arch = "i686"
git-tree-sha1 = "21d4dfc4b0ab453b7523a33cb960d20b3e0c7c29"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "aa6c5cbbb3dbbf8c58c1cc564008fd39f5ee83aafc62adf9e893e32ab85c7fba"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.i686-linux-gnu.tar.gz"
[[Tokei]]
arch = "i686"
git-tree-sha1 = "4d19af36ef2fde800e6492bd728a7d71536ad7a7"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "90e0f0b27d3097293dd6f195626272915fdf72e29e9dd0eaf3acc00add81c4aa"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.i686-linux-musl.tar.gz"
[[Tokei]]
arch = "powerpc64le"
git-tree-sha1 = "2aaf6bb12012e51481b78487d016054d811a16bc"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "7b41faafb92a8563073460f0f725f087df0f05c2ac70c1ec88cb4111f864dff6"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.powerpc64le-linux-gnu.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "54dccdc33b161432cf0916e115a3320f2306a6ed"
os = "macos"

    [[Tokei.download]]
    sha256 = "4e3d566d0d80fcd9c9c0edf0ea5c9c410d4fb2275b4ab14a91ca5b13c3956bed"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.x86_64-apple-darwin.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "6938fded2d8e3f362075ff258ad18ff71c58a482"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "5ce45b1fdcdb5148da9f93b9f559e3335008fcd76d717d4c4ad88197c165e989"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.x86_64-linux-gnu.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "11abc30d3df5af2e0dd11ff35b3ff64bc43ef7a3"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "b5841d0015ed208318a658a39119173f69766e3381a90d8e6e9f86c46b95fd04"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.x86_64-linux-musl.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "96b91948413c185088cf43c31eb287fc81194033"
os = "freebsd"

    [[Tokei.download]]
    sha256 = "d70c050c0aaf9177af8bfa30dc66682176332438a09908acee61b7fd4ebb4da7"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.x86_64-unknown-freebsd.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "aa0db9a84fde7c4dec71894cea436e3fd95fe670"
os = "windows"

    [[Tokei.download]]
    sha256 = "e1685bc0b8408199314711d364ef81858bf92996949748ca77b9d8e83a598676"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.200+0/Tokei.v12.1.200.x86_64-w64-mingw32.tar.gz"
