[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "27c9d1b9340ee8172c7bca38de97932b2940cceb"
os = "macos"

    [[Tokei.download]]
    sha256 = "bec8d5d0d122c718fc2d0a5f2069959d56ba47310d07a9f3f73d2cf4266be916"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+0/Tokei.v12.1.2.x86_64-apple-darwin.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "eb1ea0844d13d34320da40c8b1658114d5f38dff"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "22a74595f2198c40b3dbe06e1f9abcd69834a9bfa0457808f7d8873fe4f402dd"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+0/Tokei.v12.1.2.x86_64-linux-gnu.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "29a557e2d24a3e51a89a91acc1cecd70c490c6fb"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "dd76cdfb6edfcf094fcdedb3c447c9df15c0bbbe475fe2e3cd2801a8f10ec300"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+0/Tokei.v12.1.2.x86_64-linux-musl.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "661cda8f23c34e3a64f69065b4ba9566f941da7d"
os = "windows"

    [[Tokei.download]]
    sha256 = "0463830dcdbaf1608669968646bbec153c1b1379cacf1b6bbeae7229f926b8de"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+0/Tokei.v12.1.2.x86_64-w64-mingw32.tar.gz"
