[[Tokei]]
arch = "aarch64"
git-tree-sha1 = "c8cebc89748bb86c8e23ff350764c00d22f154ae"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "843c061ff2b3a754ea28ae190237cc41e2fc41f2af416f9b8e124113c03afe7a"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+2/Tokei.v12.1.2.aarch64-linux-gnu.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "3acae864fca8d5fc04e61b5ab9647182e7e3c40f"
os = "macos"

    [[Tokei.download]]
    sha256 = "2d8258bed647f7aad22862dfa88247720f9ff158703089bf71ebda9e92b37670"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+2/Tokei.v12.1.2.x86_64-apple-darwin.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "ca2ac17073dd24e3657cfeaae9dbfa8fa2276fb5"
libc = "glibc"
os = "linux"

    [[Tokei.download]]
    sha256 = "9497f984e622279959f757253b5dbfd98e86a5812014564637c82ece8484e966"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+2/Tokei.v12.1.2.x86_64-linux-gnu.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "c31dbea0a77188c662280b8481791e05b4e19922"
libc = "musl"
os = "linux"

    [[Tokei.download]]
    sha256 = "8fe5d174bab8c77d90d8fc194714c445551f66d79d57a7e362eb76b1e60f4670"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+2/Tokei.v12.1.2.x86_64-linux-musl.tar.gz"
[[Tokei]]
arch = "x86_64"
git-tree-sha1 = "3995d23f91af69ae690fe1368d3b3d434ca76e77"
os = "windows"

    [[Tokei.download]]
    sha256 = "ce8e4bb04785fbd858df735fa1066d0de8e9356fe0fcc381237ea972feeabc28"
    url = "https://github.com/JuliaBinaryWrappers/Tokei_jll.jl/releases/download/Tokei-v12.1.2+2/Tokei.v12.1.2.x86_64-w64-mingw32.tar.gz"
